/**
 * This class is generated by jOOQ
 */
package sample.jooq.domain;


import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;

import sample.jooq.domain.tables.Playground;
import sample.jooq.domain.tables.records.PlaygroundRecord;


/**
 * A class modelling foreign key relationships between tables of the <code>public</code> 
 * schema
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final Identity<PlaygroundRecord, Integer> IDENTITY_PLAYGROUND = Identities0.IDENTITY_PLAYGROUND;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final UniqueKey<PlaygroundRecord> PLAYGROUND_PKEY = UniqueKeys0.PLAYGROUND_PKEY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends AbstractKeys {
		public static Identity<PlaygroundRecord, Integer> IDENTITY_PLAYGROUND = createIdentity(Playground.PLAYGROUND, Playground.PLAYGROUND.EQUIP_ID);
	}

	private static class UniqueKeys0 extends AbstractKeys {
		public static final UniqueKey<PlaygroundRecord> PLAYGROUND_PKEY = createUniqueKey(Playground.PLAYGROUND, Playground.PLAYGROUND.EQUIP_ID);
	}
}
