/**
 * This class is generated by jOOQ
 */
package sample.jooq.domain.tables;


import java.sql.Date;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import sample.jooq.domain.Keys;
import sample.jooq.domain.Public;
import sample.jooq.domain.tables.records.PlaygroundRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Playground extends TableImpl<PlaygroundRecord> {

	private static final long serialVersionUID = -278025500;

	/**
	 * The reference instance of <code>public.playground</code>
	 */
	public static final Playground PLAYGROUND = new Playground();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<PlaygroundRecord> getRecordType() {
		return PlaygroundRecord.class;
	}

	/**
	 * The column <code>public.playground.equip_id</code>.
	 */
	public final TableField<PlaygroundRecord, Integer> EQUIP_ID = createField("equip_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.playground.type</code>.
	 */
	public final TableField<PlaygroundRecord, String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * The column <code>public.playground.color</code>.
	 */
	public final TableField<PlaygroundRecord, String> COLOR = createField("color", org.jooq.impl.SQLDataType.VARCHAR.length(25).nullable(false), this, "");

	/**
	 * The column <code>public.playground.location</code>.
	 */
	public final TableField<PlaygroundRecord, String> LOCATION = createField("location", org.jooq.impl.SQLDataType.VARCHAR.length(25), this, "");

	/**
	 * The column <code>public.playground.install_date</code>.
	 */
	public final TableField<PlaygroundRecord, Date> INSTALL_DATE = createField("install_date", org.jooq.impl.SQLDataType.DATE, this, "");

	/**
	 * Create a <code>public.playground</code> table reference
	 */
	public Playground() {
		this("playground", null);
	}

	/**
	 * Create an aliased <code>public.playground</code> table reference
	 */
	public Playground(String alias) {
		this(alias, PLAYGROUND);
	}

	private Playground(String alias, Table<PlaygroundRecord> aliased) {
		this(alias, aliased, null);
	}

	private Playground(String alias, Table<PlaygroundRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<PlaygroundRecord, Integer> getIdentity() {
		return Keys.IDENTITY_PLAYGROUND;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<PlaygroundRecord> getPrimaryKey() {
		return Keys.PLAYGROUND_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<PlaygroundRecord>> getKeys() {
		return Arrays.<UniqueKey<PlaygroundRecord>>asList(Keys.PLAYGROUND_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Playground as(String alias) {
		return new Playground(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Playground rename(String name) {
		return new Playground(name, null);
	}
}
