/**
 * This class is generated by jOOQ
 */
package sample.jooq.domain.tables.records;


import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import sample.jooq.domain.tables.Playground;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlaygroundRecord extends UpdatableRecordImpl<PlaygroundRecord> implements Record5<Integer, String, String, String, Date> {

	private static final long serialVersionUID = -1891676002;

	/**
	 * Setter for <code>public.playground.equip_id</code>.
	 */
	public void setEquipId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.playground.equip_id</code>.
	 */
	public Integer getEquipId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.playground.type</code>.
	 */
	public void setType(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.playground.type</code>.
	 */
	public String getType() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>public.playground.color</code>.
	 */
	public void setColor(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.playground.color</code>.
	 */
	public String getColor() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>public.playground.location</code>.
	 */
	public void setLocation(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.playground.location</code>.
	 */
	public String getLocation() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>public.playground.install_date</code>.
	 */
	public void setInstallDate(Date value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.playground.install_date</code>.
	 */
	public Date getInstallDate() {
		return (Date) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, String, String, String, Date> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, String, String, String, Date> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Playground.PLAYGROUND.EQUIP_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Playground.PLAYGROUND.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Playground.PLAYGROUND.COLOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Playground.PLAYGROUND.LOCATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field5() {
		return Playground.PLAYGROUND.INSTALL_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getEquipId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getColor();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getLocation();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value5() {
		return getInstallDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlaygroundRecord value1(Integer value) {
		setEquipId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlaygroundRecord value2(String value) {
		setType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlaygroundRecord value3(String value) {
		setColor(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlaygroundRecord value4(String value) {
		setLocation(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlaygroundRecord value5(Date value) {
		setInstallDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlaygroundRecord values(Integer value1, String value2, String value3, String value4, Date value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PlaygroundRecord
	 */
	public PlaygroundRecord() {
		super(Playground.PLAYGROUND);
	}

	/**
	 * Create a detached, initialised PlaygroundRecord
	 */
	public PlaygroundRecord(Integer equipId, String type, String color, String location, Date installDate) {
		super(Playground.PLAYGROUND);

		setValue(0, equipId);
		setValue(1, type);
		setValue(2, color);
		setValue(3, location);
		setValue(4, installDate);
	}
}
